[package]
name = "flume"
version = "0.7.1"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"
description = "A blazingly fast multi-producer channel"
repository = "https://github.com/zesterer/flume"
keywords = ["mpsc", "fifo", "channel", "thread", "fast"]
categories = ["concurrency", "data-structures"]
license = "Apache-2.0/MIT"
readme = "README.md"

[features]
select = []
async = ["futures"]
default = ["select", "async"]

[dependencies]
spin = "0.5"
futures = { version = "^0.3", default-features = false, optional = true }
loom = { version = "0.3", optional = true }

[dev-dependencies]
crossbeam-channel = "0.4"
crossbeam-utils = "0.7"
criterion = "0.3.1"
async-std = { version = "1.5", features = ["attributes"] }

[[bench]]
name = "basic"
harness = false
